name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & State Management
  flutter_riverpod: ^2.4.9
  equatable: ^2.0.5

  # Google AI
  google_generative_ai: ^0.4.7

  # UI & Fonts
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.6
  intl: ^0.19.0

  path_provider: ^2.1.5
  flutter_tts: ^4.2.3
  speech_to_text: ^7.3.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  http: ^1.6.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  build_runner: ^2.4.7
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
