name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & State Management
  flutter_riverpod: ^2.4.9
  equatable: ^2.0.5

  # Google AI
  google_generative_ai: ^0.4.7

  # UI & Fonts
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.6
  intl: ^0.20.2

  path_provider: ^2.1.5
  flutter_tts: ^4.2.3
  speech_to_text: ^7.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.6.0
  shared_preferences: ^2.5.3
  share_plus: ^10.1.3
  file_picker: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
